name: CI/CD

on: 
  push:
    branches: [ "main" ]

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Welcome Message
        run: echo "This is my first action"
        
      - name: List the Files
        run: ls
